# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode12.3
xcode_workspace: ODScrollView.xcworkspace
xcode_scheme: ODScrollView-Example
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro Max
before_install:
- gem install cocoapods
- cd Example
- pod install
